serverName: 'xlab'
broadcast: false
switchTime: 60
servers:
  - man10
  - shigen
  - casino
  - login
  - market
mc1:
  camera: camera1
mc2:
  camera: camera2
mc3:
  camera: camera3
mc4:
  camera: camera4
