mc1:
  camera: camera1
  location: location1
  boardcast: https://www.youtube.com/@man10server でライブ配信中！
mc2:
  camera: camera2
  location: location2
mc3:
  camera: camera3
  location: location3
mc4:
  camera: camera4
  location: location4